name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Version Checking
      run: |
        npm version
    - name: Build
      run: |
        npm install
        npm run build
    - name: Firebase Deploy
      run: |
        firebase use "abs-hornbill-metal" --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
