name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Firebase Deploy
      run: |
        sudo npm i -g firebase-tools --unsafe-perm
        firebase use "abs-hornbill-metal" --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
