name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Firebase Deploy
      run: |
        sudo npm install -g firebase-tools
        firebase use abs-hornbill-metal --token $FIREBASE_TOKEN
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
